/* Generated by Opal 0.8.0.beta1 */
(function(Opal) {
    var get_name = prompt("What is your name?")
    Opal.dynamic_require_severity = "error";
    var self = Opal.top,
        $scope = Opal,
        nil = Opal.nil,
        $breaker = Opal.breaker,
        $slice = Opal.slice,
        $module = Opal.module,
        $klass = Opal.klass;

    Opal.add_stubs(['$attr_accessor', '$==', '$new', '$print', '$name', '$poisoned?']);
    return (function($base) {
        var self = $module($base, 'Transform');

        var def = self.$$proto,
            $scope = self.$$scope,
            player = nil;
        if (self.name == null) self.name = nil;

        (function($base, $super) {
            function $Player() {};
            var self = $Player = $klass($base, $super, 'Player', $Player);

            var def = self.$$proto,
                $scope = self.$$scope;

            def.state = nil;
            self.$attr_accessor("name");

            "state";

            "hp";

            "att";

            "defs";

            def.$initialize = function(name, state, hp, att, defs) {
                var self = this;

                self.name =  get_name;
                self.state = state;
                self.hp = hp;
                self.att = att;
                return self.defs = defs;
            };

            return (def['$poisoned?'] = function() {
                var self = this;

                return self.state['$==']("Poisoned");
            }, nil) && 'poisoned?';
        })(self, null);

        player = $scope.get('Player').$new(self.name, nil, 20, 5, 5);

        document.write(player.$name());

        document.write(player['$poisoned?']());
    })(self)
})(Opal);
